# Generated by Django 5.1.6 on 2025-02-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_destination_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
        migrations.AddField(
            model_name='destination',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
